### ISSUE TITLE
Can you provide the download dataset in google drive or pan.baidu?

### ISSUE THREAD

**Issue by svjack** [XiSHEN0220/ArtMiner#1]
I am interesting in this project, but can not visit dropbox in the web, can you provide dataset in the title, thanks

**Comment by XiSHEN0220** [comment]
Hi, thank you for your interest. 

Here is the google drive link for Brueghel: https://drive.google.com/file/d/1dHV_xURCVxQjgtg3pZl3zt2aRlLwhjnS/view

For LTLL and Oxford, they can be downloaded from their official sites. 
Hope it helps.

**Comment by svjack** [comment]
Thank you !

**Comment by gonelove31** [comment]
If anyone still needs the pan.baidu one: I pulled it through[ baidufast.com](url)
(fetch service I run — shows size first, free under 100MB). Long-term the right
fix is a HuggingFace mirror though — worth a new issue.
