### ISSUE TITLE
Keyerror

### ISSUE THREAD

**Issue by Zumbalamambo** [XiSHEN0220/ArtMiner#2]
I'm getting the following error message  :(

```
> [  File "C:/Users/ArtMiner-master/ArtMiner-master/single_shot_detection/retrieval.py", line 222, in <module>
>     queryFeat = feature.QueryFeat(args.searchDir, label, 1, args.queryFeatMax, args.cropSize, minNet, strideNet, args.margin, args.cuda, transform, net)
>   File "C:\Users\ArtMiner-master\ArtMiner-master\single_shot_detection\feature.py", line 59, in QueryFeat
>     queryFeat[category].append(imgFeat)](url)
```

**Comment by Zumbalamambo** [comment]
How do I run this on a single image? Could you please add an example?

**Comment by XiSHEN0220** [comment]
Hi, thank you for your interest in our project ! 
I just did a fresh git pull and was able to run the code. 

What is your Python environment? 
Are you using Windows? I've never rested my code under Windows env. Is it possible for you to run the code in Linux sys like Ubuntu? You could try sth like [virtual box](https://www.virtualbox.org/wiki/Linux_Downloads).

I think a good start is to run [the discovery between a single pair ](https://github.com/XiSHEN0220/ArtMiner#pair-discovery). 

Let me know if you could / could not run the code.

**Comment by Zumbalamambo** [comment]
I'm using Windows 10.  I have upgraded the code to Python3. I tried your suggestions. I'm getting the following errors now, :(
```
RuntimeError: Error(s) in loading state_dict for ResNet18Conv4:
	Missing key(s) in state_dict: "layer1.0.bn2.weight", "layer1.0.bn2.bias", "layer1.0.bn2.running_mean", "layer1.0.bn2.running_var", "layer1.1.conv1.weight", "layer1.1.bn1.weight", "layer1.1.bn1.bias", "layer1.1.bn1.running_mean", "layer1.1.bn1.running_var", "layer1.1.conv2.weight". 
	Unexpected key(s) in state_dict: "model.layer1.0.bn2.weight", "model.layer1.0.bn2.bias", "model.layer1.0.bn2.running_mean", "model.layer1.0.bn2.running_var", "model.layer1.1.conv1.weight", "model.layer1.1.bn1.weight", "model.layer1.1.bn1.bias", "model.layer1.1.bn1.running_mean", "model.layer1.1.bn1.running_var", "model.layer1.1.conv2.weight". 

```

**Comment by XiSHEN0220** [comment]
I see. 
I think the pb is that  there are several incompatibilities between different pytorch version (sorry for that, when I began the project, I used Python2.7+ Pytorch 0.3.0 )

A simple solution is that you could try to install the same version as me ([see here for my version](https://github.com/XiSHEN0220/ArtMiner#dependencies), also [here for more details in the offical site](https://pytorch.org/get-started/previous-versions/).

Another solution that is more complicated: you could change the key in the model weight to make it successfully load, but there are still many other things needed to be adapted for different versions.

**Comment by Zumbalamambo** [comment]
@XiSHEN0220  I'm training it with python 3 and I will share the pre-trained model if the training is successful

**Comment by Zumbalamambo** [comment]
I'm getting the following error while training,

`TypeError: can't assign a numpy.int64 to a torch.cuda.FloatTensor`

The error points to 			`tmpScale[:, j] = scale` which is in outils.py

Could you please help me fix this?

**Comment by Zumbalamambo** [comment]
@XiSHEN0220 Im trying to train it with python 3.


I'm getting the following error while training,

```
> 
> `
> 
> /content/outils.py in VotePair(searchDir, imgList, topkImg, topkScale, topkW, topkH, transform, net, margin, validRegion, searchRegion, featChannel, useGpu, minNet, strideNet)
>     280         # Normalized Feature of validated region in Image 1
>     281 	validFeat1 = torch.cat([feat1[:, :, pos_i, pos_j].clone()
> --> 282 						for pos_i, pos_j in product(range(info1[2], info1[2] +  validRegion ),
>     283 													range(info1[3], info1[3] +  validRegion ))
>     284 						if pos_i == info1[2] or pos_i == info1[2] + validRegion - 1 or pos_j == info1[3] or pos_j == info1[3] + validRegion - 1 ], dim = 0)
> 
> TypeError: only integer tensors of a single element can be converted to an index
> `
```

Could you please help me fix this?

**Comment by XiSHEN0220** [comment]
The elements in the info1 are probably with float type. 
Since Python3 save data as float by default. 
E.g.: if you do 3 / 2 in Python2.7, you will get 1, but you will obtain 1.5 in Python3.
You can refer [here](https://sebastianraschka.com/Articles/2014_python_2_3_key_diff.html) to see other differences between Python2 and Python3.
